version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: slava010/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media # app - созданная директория в Dockerfile backenda; media из settings.py
    depends_on:
      - db
  frontend:
    env_file: .env
    image: slava010/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: slava010/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/staticfiles/media # директорую указать как в конфиге Nginx при настройке location
    depends_on:
      - backend